In [1]:
# Import the neccessary modules needed
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import pandas as pd

In [17]:
# Create a function that will extract the names and h-indices of computer science professors
def extract_data(num_of_pages):
    # Create a dataframe to store the names of the professors and their h-indices
    computer_professors = pd.DataFrame(columns=['Name', 'H-Index'])

    # Set the browser to be used (We will be using Mozilla Firefox)
    firefox_driver = webdriver.Firefox(executable_path='.\Drivers\geckodriver.exe')

    # Set the url of website to search and set the search phrase
    search_phrase = "Computer Science Professors"
    url = 'https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=Computer+Science+Professors&after_author=IIoAANOS__8J&astart=250'

    # set a timeout
    firefox_driver.set_page_load_timeout(20)
    firefox_driver.get(url)
    # Number of page to search
    pages = range(1, num_of_pages+1)
    # Click on each link
    for page in pages:
        for i in range(26,27):
            i = str(i)
            try:
                firefox_driver.find_element_by_css_selector('#gsc_sa_ccl > div:nth-child({}) > div > div > h3 > a'.format(i)).click()
                h_index = firefox_driver.find_element_by_css_selector('#gsc_rsb_st > tbody > tr:nth-child(2)')
                name = firefox_driver.find_element_by_css_selector('#gsc_prf_in')
                computer_professors = computer_professors.append({'Name': name.text , 'H-Index':h_index.text.split()[1] }, ignore_index=True)
                print(name.text)
                time.sleep(10)
                firefox_driver.back()
                time.sleep(10)
            except:
                pass
        # click on the next page
        firefox_driver.find_element_by_css_selector('#gsc_authors_bottom_pag > div > button.gs_btnPR.gs_in_ib.gs_btn_half.gs_btn_lsb.gs_btn_srt.gsc_pgn_pnx').click()
    # Sleep and close the browser
    time.sleep(20)
    firefox_driver.quit()

In [3]:
# Call the function that will extract the data, passing in the number of pages to extract
extract_data(25)

Empty DataFrame
Columns: [Name, H-Index]
Index: []

In [21]:
# Concatenate all the csv files into 1
data1 = pd.read_csv("Computer_Professors20.csv")
data2 = pd.read_csv("Computer_Professors24.csv")
data3 = pd.read_csv("Computer_Professors25.csv")

In [22]:
data2

                         Name  H-Index
0                Martin Ester       59
1                 Barry Smith       89
2            Olvi Mangasarian       85
3               Shwetak Patel       56
4            Alexander C Berg       48
5                 Roch Guerin       63
6                 Yolanda Gil       61
7          Michael J. Pazzani       64
8               Jose Meseguer       80
9              Michael R. Lyu       86
10              Steven H. Low       82
11                Jörg Sander       43
12  João Paulo Domingos Silva       77
13             Thomas Hofmann       56
14                Daniel Keim       74
15                   Raj Jain       62
16         Andrew T. Campbell       81
17                Thomas Brox       72
18                 Eva Tardos       64
19                 L. Jay Guo       72
20        Dimitris N. Metaxas       88
21              David Forsyth       77
22     Enrique Herrera-Viedma       88
23      Gill Harmandeep Singh       72
24              Andrew Ortony       53
25               David Blaauw       84
26              Ronald Fedkiw       66
27           Arnold Smeulders       60
28            George Varghese       82
29                Piotr Indyk       72
30              Srini Devadas       89
31            Gabor T. Herman       70
32                Henry Kautz       77
33                Lillian Lee       38
34             Mohan varshney       85
35            Diego Calvanese       68
36           Allen Tannenbaum       76
37               Franz Baader       60
38               Rick Stevens       53
39                Steve Seitz       70

In [23]:
data1 = data1.iloc[0:190, :]

In [26]:
data = pd.concat([data1, data2]).reset_index(drop=True)
data = pd.concat([data, data3]).reset_index(drop=True)

In [27]:
len(data)

250